/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { getNLSLanguage } from '../../../../../nls.js';

const simplifiedChineseMessages: Readonly<Record<string, string>> = Object.freeze({
	copy: '复制',
	'shuncodeBridge.title': 'ShunCode Bridge',
	'shuncodeBridge.descriptionShort': '将当前工作区工具连接到 ChatGPT 或其他远程 MCP 客户端。',
	'shuncodeBridge.loadingStatus': '正在检查 Bridge 状态…',
	'shuncodeBridge.publicUrl': 'MCP 地址',
	'shuncodeBridge.copyUrl': '复制 MCP 地址',
	'shuncodeBridge.start': '启动 Bridge',
	'shuncodeBridge.stop': '停止 Bridge',
	'shuncodeBridge.openChatGpt': '打开 ChatGPT',
	'shuncodeBridge.openChatGptInBrowser': '在 ShunCode 内置浏览器中打开 chatgpt.com',
	'shuncodeBridge.openArena': '打开 Arena',
	'shuncodeBridge.openArenaInBrowser': '在 ShunCode 内置浏览器中打开 arena.ai',
	'shuncodeBridge.openWorkBuddy': '打开 WorkBuddy',
	'shuncodeBridge.openWorkBuddyInBrowser': '在 ShunCode 内置浏览器中打开 workbuddy.cn',
	'shuncodeBridge.openTraeWork': '打开 Trae',
	'shuncodeBridge.openTraeWorkInBrowser': '在 ShunCode 内置浏览器中打开 work.trae.cn',
	'shuncodeBridge.openQwenWork': '打开 Qwen',
	'shuncodeBridge.openQwenWorkInBrowser': '在 ShunCode 内置浏览器中打开 qwenwork.cn',
	'shuncodeBridge.openManus': '打开 Manus',
	'shuncodeBridge.openManusInBrowser': '在 ShunCode 内置浏览器中打开 manus.im',
	'shuncodeBridge.openShunova': '打开 Shunova',
	'shuncodeBridge.openShunovaInBrowser': '在 ShunCode 内置浏览器中打开 shunova.cc',
	'shuncodeBridge.copyPrompt': '复制提示词',
	'shuncodeBridge.copyPromptTitle': '复制当前 MCP 地址与连接提示词',
	'shuncodeBridge.securityWarningShort': 'Bridge 可以编辑文件并运行终端命令。请勿公开 MCP 地址。',
	'shuncodeBridge.accountAccess': '账号与授权',
	'shuncodeBridge.accessLoading': '正在检查 GitHub 账号和 Bridge 授权…',
	'shuncodeBridge.installationId': '当前安装 ID',
	'shuncodeBridge.copyInstallationId': '复制安装 ID',
	'shuncodeBridge.installationIdHelp': '使用此 ID 在授权管理后台中识别当前设备。',
	'shuncodeBridge.githubSignIn': '使用 GitHub 登录',
	'shuncodeBridge.giteeSignIn': '使用 Gitee 登录',
	'shuncodeBridge.giteeWaitingTitle': '正在等待 Gitee 授权…',
	'shuncodeBridge.giteeWaiting': 'Gitee 授权页面应在浏览器中打开，请完成授权后返回 ShunCode。',
	'shuncodeBridge.signInInProgress': 'Bridge 登录正在进行中。请完成或取消后重试。',
	'shuncodeBridge.refreshLoginStatus': '刷新登录状态',
	'shuncodeBridge.refreshLicense': '刷新授权',
	'shuncodeBridge.signOut': '退出登录',
	'shuncodeBridge.purchaseTitle': '购买 Bridge 授权',
	'shuncodeBridge.renewTitle': '续费 Bridge 授权',
	'shuncodeBridge.purchaseHelp': '选择服务端提供的套餐。结算页面将在浏览器中打开，支付确认后 ShunCode 会自动激活 Bridge。',
	'shuncodeBridge.paymentPlan': '套餐',
	'shuncodeBridge.paymentType': '支付方式',
	'shuncodeBridge.purchase': '购买',
	'shuncodeBridge.renew': '续费',
	'shuncodeBridge.checkPayment': '检查支付状态',
	'shuncodeBridge.activationCode': '激活码',
	'shuncodeBridge.redeem': '兑换',
	'shuncodeBridge.connectionSettings': '连接设置',
	'shuncodeBridge.connectionChecking': '正在检查隧道设置…',
	'shuncodeBridge.checking': '检查中',
	'shuncodeBridge.setupRequired': '需要配置',
	'shuncodeBridge.ready': '已就绪',
	'shuncodeBridge.connectionErrorSummary': 'Bridge 连接需要处理',
	'shuncodeBridge.tunnelProvider': '隧道模式',
	'shuncodeBridge.cloudflareQuickTunnel': 'Cloudflare Quick Tunnel（无需账号或域名）',
	'shuncodeBridge.cloudflareRecommended': '默认 · 零配置',
	'shuncodeBridge.cloudflareModeSummary': '每次重启 Bridge 都会生成新地址，适合优先考虑配置简单、不要求永久地址的场景。',
	'shuncodeBridge.cloudflareModeAddress': '地址：临时地址，重启后变化',
	'shuncodeBridge.cloudflareModeLimits': '限制：官方未列出每月请求额度；最多 200 个并发请求；无 SLA',
	'shuncodeBridge.cloudflareModeSetup': '配置：只需安装 cloudflared，无需账号或域名',
	'shuncodeBridge.cloudflareNamedTunnel': 'Cloudflare Named Tunnel',
	'shuncodeBridge.cloudflareNamedStableAddress': '固定地址',
	'shuncodeBridge.cloudflareNamedModeSummary': '使用 Cloudflare 管理的固定主机名，ShunCode 重启后地址保持不变。',
	'shuncodeBridge.cloudflareNamedModeAddress': '地址：Cloudflare 托管域名中的固定主机名',
	'shuncodeBridge.cloudflareNamedModeLimits': '限制：没有 ngrok 式的每月 20,000 次请求额度',
	'shuncodeBridge.cloudflareNamedModeSetup': '配置：Cloudflare 账号、域名、Tunnel Token 和 Published application 路由',
	'shuncodeBridge.ngrokReservedTunnel': 'ngrok 开发域名',
	'shuncodeBridge.ngrokStableAddress': '固定地址',
	'shuncodeBridge.ngrokModeSummary': '账号分配的开发域名可在重启后继续使用，ChatGPT 中的 MCP 地址通常无需修改。',
	'shuncodeBridge.ngrokModeAddress': '地址：固定地址，重启后可复用',
	'shuncodeBridge.ngrokModeLimits': '免费额度：每月 20,000 次 HTTP/S 请求和 1 GB 出站流量',
	'shuncodeBridge.ngrokModeSetup': '配置：ngrok 账号、Authtoken 和账号分配的开发域名',
	'shuncodeBridge.tunnelProviderHelp': '请在上方选择模式。切换隧道模式前需要先停止 Bridge。',
	'shuncodeBridge.cloudflareNamedConfiguration': 'Cloudflare Named Tunnel 配置',
	'shuncodeBridge.cloudflareNamedHostname': '公网主机名',
	'shuncodeBridge.cloudflareTunnelToken': 'Tunnel Token',
	'shuncodeBridge.cloudflareTunnelTokenPlaceholder': '粘贴 Token 以设置或替换',
	'shuncodeBridge.cloudflareNamedLocalPort': '固定本地端口',
	'shuncodeBridge.cloudflareNamedServiceUrl': 'Cloudflare Service URL',
	'shuncodeBridge.cloudflareNamedServiceHelp': '在 Cloudflare Tunnels 中，Published application 的主机名必须与上方公网主机名一致，Service URL 必须与此本地地址完全一致。',
	'shuncodeBridge.saveNamedTunnel': '保存 Named Tunnel',
	'shuncodeBridge.clearTunnelToken': '清除 Token',
	'shuncodeBridge.cloudflareTunnelTokenSaved': 'Token 已安全保存。输入框留空可继续使用当前 Token。',
	'shuncodeBridge.cloudflareTunnelTokenMissing': '尚未保存 Token。',
	'shuncodeBridge.cloudflareNamedHostnameRequired': '请输入 Cloudflare 公网主机名。',
	'shuncodeBridge.cloudflareNamedPortRequired': '请输入 1024 至 65535 之间的本地端口。',
	'shuncodeBridge.cloudflareTunnelTokenRequired': '保存前请粘贴 Cloudflare Tunnel Token。',
	'shuncodeBridge.clearTunnelTokenConfirm': '清除 Cloudflare Tunnel Token？',
	'shuncodeBridge.clearTunnelTokenConfirmDetail': '保存新的 Token 前，Cloudflare Named Tunnel 将无法启动。',
	'shuncodeBridge.namedTunnelConfigurationRequired': '启动 Bridge 前，请先保存 Cloudflare 主机名和 Tunnel Token。',
	'shuncodeBridge.cloudflareNotInstalledSummary': '尚未安装 cloudflared',
	'shuncodeBridge.ngrokNotInstalledSummary': '尚未安装 ngrok',
	'shuncodeBridge.ngrokConfigAttentionSummary': 'ngrok 配置需要处理',
	'shuncodeBridge.domainMissingSummary': '尚未设置保留域名',
	'shuncodeBridge.cloudflareReadySummary': 'Cloudflare Quick Tunnel 已就绪 · 重启后临时地址会变化',
	'shuncodeBridge.cloudflareNamedReadySummary': 'Cloudflare Named Tunnel 已就绪 · {0}',
	'shuncodeBridge.cloudflareNamedConfigAttentionSummary': 'Cloudflare Named Tunnel 配置需要处理',
	'shuncodeBridge.namedHostnameMissingSummary': '尚未设置 Cloudflare 主机名',
	'shuncodeBridge.connectionReadySummary': 'ngrok 已就绪 · {0}',
	'shuncodeBridge.domain': 'ngrok 域名',
	'shuncodeBridge.domainHelpShort': '请输入 ngrok 控制台中的保留域名。',
	'shuncodeBridge.tunnelStatus': '隧道状态',
	'shuncodeBridge.tunnelUnchecked': '尚未检查隧道客户端。',
	'shuncodeBridge.checkTunnel': '检查隧道',
	'shuncodeBridge.installCloudflaredNow': '一键安装 cloudflared',
	'shuncodeBridge.installingCloudflared': '正在通过 Winget 安装 cloudflared…',
	'shuncodeBridge.installingCloudflaredShort': '正在安装…',
	'shuncodeBridge.cloudflaredInstalled': '已安装',
	'shuncodeBridge.ngrokStatus': 'ngrok 状态',
	'shuncodeBridge.ngrokUnchecked': '尚未检查 ngrok。',
	'shuncodeBridge.checkNgrok': '检查 ngrok',
	'shuncodeBridge.persistentMode': '随 ShunCode 启动 Bridge',
	'shuncodeBridge.persistentModeHelpShort': '应用准备完成后自动打开并启动 Bridge。',
	'shuncodeBridge.persistentLicenseRequired': '启用自动启动前，请先激活 Bridge 授权。',
	'shuncodeBridge.advancedSettings': '高级设置',
	'shuncodeBridge.transport': '传输协议',
	'shuncodeBridge.streamableHttp': 'Streamable HTTP',
	'shuncodeBridge.connectionDiagnostics': '连接诊断',
	'shuncodeBridge.openSession': '打开 Bridge 会话',
	'shuncodeBridge.securityAccess': '安全与访问',
	'shuncodeBridge.resetAddressHelp': '如果 MCP 地址已经泄露，请重置其中的秘密路径。所有使用旧地址的客户端都将停止工作。',
	'shuncodeBridge.resetMcpAddress': '重置 MCP 地址',
	'shuncodeBridge.exposedTools': '已开放工具',
	'shuncodeBridge.configureCloudflare': '安装 cloudflared',
	'shuncodeBridge.cloudflareConfigurationHelp': 'cloudflared 配置帮助',
	'shuncodeBridge.configureCloudflareNamed': '配置 Cloudflare Named Tunnel',
	'shuncodeBridge.cloudflareNamedConfigurationHelp': 'Cloudflare Named Tunnel 配置帮助',
	'shuncodeBridge.cloudflareNamedSetupIntro': '创建远程管理的 Cloudflare Tunnel，复制 Token，并将固定主机名发布到上方 ShunCode Service URL。',
	'shuncodeBridge.createCloudflareTunnel': '创建或打开 Cloudflare Tunnel 并复制 Token',
	'shuncodeBridge.openCloudflareTunnels': '打开 Cloudflare Tunnels',
	'shuncodeBridge.publishCloudflareHostname': '添加 Published application 路由',
	'shuncodeBridge.publishCloudflareHostnameHelp': '将公网主机名设置为上方保存的值，并将 Service URL 设置为 ShunCode 显示的完整 http://127.0.0.1:<端口> 地址。',
	'shuncodeBridge.reviewCloudflareDns': '检查主机名 DNS 记录',
	'shuncodeBridge.openCloudflareDns': '打开 Cloudflare DNS',
	'shuncodeBridge.cloudflareSetupIntro': '只需安装一次 cloudflared。Quick Tunnel 无需 Cloudflare 账号、Token 或域名。',
	'shuncodeBridge.installCloudflared': '安装或更新 cloudflared',
	'shuncodeBridge.downloadCloudflared': '打开官方下载页面',
	'shuncodeBridge.verifyCloudflared': '验证 cloudflared',
	'shuncodeBridge.cloudflareAddressHelp': '每次启动 Bridge 都会生成新的临时 MCP 地址。ShunCode 会自动复制，请在 ChatGPT 中更新该地址。',
	'shuncodeBridge.namedTunnelStartingDetail': '正在连接固定 Cloudflare 主机名…',
	'shuncodeBridge.namedTunnelStoppedDetail': 'Bridge 已停止，固定 Cloudflare 主机名当前未连接。',
	'shuncodeBridge.namedHostnameRequiredSummary': '启动前请配置 Cloudflare 主机名和 Tunnel Token。',
	'shuncodeBridge.cloudflareNamedInvalidAction': 'cloudflared 已安装，但主机名、Tunnel Token 或 Service URL 需要处理。',
	'shuncodeBridge.configureNgrok': '配置 ngrok',
	'shuncodeBridge.setupIntro': '请在 Windows PowerShell 中执行以下一次性配置。安装完成后重启 ShunCode，使扩展主机能够找到 ngrok。',
	'shuncodeBridge.installNgrok': '安装或更新 ngrok',
	'shuncodeBridge.downloadNgrok': '打开官方下载页面',
	'shuncodeBridge.addAuthtoken': '添加 ngrok Authtoken',
	'shuncodeBridge.openAuthtoken': '打开 Authtoken 页面',
	'shuncodeBridge.verifyNgrok': '验证安装和配置',
	'shuncodeBridge.reserveDomain': '选择免费的保留域名',
	'shuncodeBridge.openDomains': '打开域名页面',
	'shuncodeBridge.purchaseRequired': '启动 Bridge 前，请先购买套餐或使用激活码开通授权。',
	'shuncodeBridge.signInRequired': '启动 Bridge 前，请先使用 GitHub 登录。',
	'shuncodeBridge.domainRequired': '启动 Bridge 前，请输入 ngrok 保留域名。',
	'shuncodeBridge.signOutConfirm': '退出 Bridge 登录？',
	'shuncodeBridge.signOutConfirmDetail': '正在运行的 Bridge 将停止。已购买的授权仍会保留在此 GitHub 账号下。',
	'shuncodeBridge.planRequired': '请选择 Bridge 套餐。',
	'shuncodeBridge.activationRequired': '请输入 Bridge 激活码。',
	'shuncodeBridge.resetAddressConfirm': '重置 MCP 地址？',
	'shuncodeBridge.resetAddressConfirmDetail': '当前 MCP 地址将立即失效。请更新 ChatGPT 和所有其他客户端中的地址。',
	'shuncodeBridge.actionRequired': '需要处理',
	'shuncodeBridge.authorized': '已授权',
	'shuncodeBridge.notActive': '未开通',
	'shuncodeBridge.signInRequiredBadge': '登录',
	'shuncodeBridge.serviceUnavailableSummary': 'Bridge 授权服务不可用',
	'shuncodeBridge.notConfigured': '当前 ShunCode 构建未包含 Bridge 授权信任锚。',
	'shuncodeBridge.accountNeedsAttention': '{0} · 授权需要处理',
	'shuncodeBridge.accessNeedsAttention': 'Bridge 授权需要处理',
	'shuncodeBridge.accountNotConnected': '尚未连接账号',
	'shuncodeBridge.signedOutDetailShort': '使用 GitHub 或 Gitee 登录后可检查或购买 Bridge 授权。',
	'shuncodeBridge.lifetimeAccess': '永久顺',
	'shuncodeBridge.expiresAt': '授权有效至 {0}',
	'shuncodeBridge.activeAccess': '授权有效',
	'shuncodeBridge.accountLicensedCompact': '{0} · {1} · 当前设备已授权',
	'shuncodeBridge.accountManagement': '可在此管理安装 ID、刷新授权或退出登录。',
	'shuncodeBridge.accountUnlicensedCompact': '{0} · Bridge 尚未开通',
	'shuncodeBridge.accountUnlicensed': '购买套餐或兑换激活码后即可使用 Bridge。',
	'shuncodeBridge.alipay': '支付宝',
	'shuncodeBridge.plansUnavailable': '当前无法获取支付套餐。请刷新授权服务后重试。',
	'shuncodeBridge.plansLoadFailed': '无法加载支付套餐：{0}',
	'shuncodeBridge.paymentPending': '等待支付 · {0} · ¥{1}。请在浏览器中完成支付，本页面会自动检查订单。',
	'shuncodeBridge.paymentPaid': '支付已确认，正在刷新 Bridge 授权…',
	'shuncodeBridge.paymentStatus': '最近一笔支付：{0} · {1}。',
	'shuncodeBridge.unknown': '未知',
	'shuncodeBridge.paymentOrderStatus.pending': '等待支付',
	'shuncodeBridge.paymentOrderStatus.paid': '已支付',
	'shuncodeBridge.paymentOrderStatus.expired': '已过期',
	'shuncodeBridge.paymentOrderStatus.failed': '支付失败',
	'shuncodeBridge.paymentOrderStatus.cancelled': '已取消',
	'shuncodeBridge.paymentOrderStatus.canceled': '已取消',
	'shuncodeBridge.running': '运行中',
	'shuncodeBridge.starting': '正在启动…',
	'shuncodeBridge.error': '错误',
	'shuncodeBridge.stopped': '已停止',
	'shuncodeBridge.runningDetailCompact': '远程端点已开启 · {0} 个活动请求',
	'shuncodeBridge.startingDetail': '正在开启安全 MCP 端点…',
	'shuncodeBridge.bridgeErrorDetail': 'Bridge 启动失败。',
	'shuncodeBridge.healthCheckTimedOutHint': '公网健康检查超时。本机可能无法直接访问公网端点。请配置 http.proxy 代理或开启系统/全局（TUN）代理后重试。',
	'shuncodeBridge.healthCheckUnreachableHint': '本机无法访问公网 Bridge 端点（可能被网络环境阻断）。请配置 http.proxy 代理或开启系统/全局（TUN）代理后重试。',
	'shuncodeBridge.cloudflaredEdgeBlockedHint': 'cloudflared 无法连接 Cloudflare 边缘（QUIC/UDP 7844）。普通 HTTP 代理对 cloudflared 无效，请开启系统/全局（TUN）代理后重试。',
	'shuncodeBridge.stoppedDetailCompact': 'Bridge 已停止，当前没有公开端点。',
	'shuncodeBridge.domainRequiredSummary': '请先在“连接设置”中填写 ngrok 域名。',
	'shuncodeBridge.quickTunnelStartingDetail': '正在生成新的 Cloudflare 临时 MCP 地址…',
	'shuncodeBridge.quickTunnelStoppedDetail': '启动 Bridge 后将自动生成 Cloudflare 临时 MCP 地址。',
	'shuncodeBridge.quickTunnelRecoveryDetail': '上一个临时地址已失效，正在生成并复制替代地址…',
	'shuncodeBridge.quickTunnelAddressCopied': '临时 MCP 地址已复制。每次 Bridge 重启后，请在 ChatGPT 中替换 MCP 地址。',
	'shuncodeBridge.cloudflareMissingAction': '尚未安装 cloudflared，请完成下方一次性配置。',
	'shuncodeBridge.ngrokMissingAction': '尚未安装 ngrok，请完成下方配置。',
	'shuncodeBridge.ngrokInvalidAction': 'ngrok 已安装，但 Authtoken 或配置需要处理。',
	'shuncodeBridge.ngrokDomainMissing': 'ngrok 已就绪，请在上方填写保留域名。',
	'shuncodeBridge.ngrokReady': '已就绪',
	'shuncodeBridge.tunnelReady': '已就绪',
	'shuncodeBridge.ngrokConfigurationHelp': 'ngrok 配置帮助',
	'shuncodeBridge.bridgeOnlyTodos': '仅 Bridge 可用的持久任务状态工具',
	'shuncodeBridge.bridgeOnly': '仅 Bridge 可用的进度报告工具',
	'shuncodeBridge.persistentModeOn': '重启后将自动打开并启动 Bridge',
	'shuncodeBridge.persistentModeOff': 'ShunCode 将以聊天模式启动',
	'shuncodeBridge.navigationLabel': 'Bridge',
	'shuncodeBridge.navigationDescription': '将 ShunCode 工具作为远程 Streamable HTTP MCP 端点开放。',
	'shuncodeBridge.autoStartFailed': 'Bridge 自动启动失败：{0}',
	'shuncodeBridge.quickLinks': '快速打开',
	'shuncodeBridge.quickLinksHelp': '在这里添加的快捷方式会显示在本页顶部，点击后在 ShunCode 内置浏览器中打开。',
	'shuncodeBridge.quickLinkNamePlaceholder': '名称',
	'shuncodeBridge.quickLinkUrlPlaceholder': 'https://…',
	'shuncodeBridge.quickLinkAdd': '添加',
	'shuncodeBridge.quickLinkOpen': '打开',
	'shuncodeBridge.quickLinkDelete': '删除',
	'shuncodeBridge.quickLinkDeleteConfirm': '删除快速打开『{0}』？',
	'shuncodeBridge.quickLinkDeleteConfirmDetail': '该按钮将从本页顶部移除。',
	'shuncodeBridge.quickLinkNameRequired': '请输入快捷方式名称。',
	'shuncodeBridge.quickLinkUrlInvalid': '请输入有效的 http:// 或 https:// 地址。',
	'shuncodeBridge.quickLinkUrlDuplicate': '该地址已在列表中。',
	'shuncodeBridge.quickLinksEmpty': '还没有自定义快捷方式。',
});

function isSimplifiedChinese(): boolean {
	const language = getNLSLanguage()?.toLowerCase();
	return language === 'zh-cn' || language === 'zh-hans' || language?.startsWith('zh-hans-') === true;
}

export function localizeBridge(key: string, message: string, ...args: (string | number | boolean | undefined | null)[]): string {
	const translated = isSimplifiedChinese() ? simplifiedChineseMessages[key] ?? message : message;
	return translated.replace(/\{(\d+)\}/g, (match, index: string) => {
		const value = args[Number(index)];
		return value === undefined || value === null ? String(value) : String(value);
	});
}
