export interface BridgeLicenseBuildConfig {
  readonly serverUrl: string;
  readonly issuer: string;
  readonly audience: string;
  readonly publicKeyPem: string;
  /** Gitee OAuth application client id. Empty disables Gitee sign-in. */
  readonly giteeClientId?: string;
}

/**
 * Production Bridge licensing trust anchor.
 *
 * Generated by bridge-license-worker/scripts/configure-client.mjs. The private
 * signing key must remain only in Cloudflare Worker secrets.
 */
export const BRIDGE_LICENSE_BUILD_CONFIG: BridgeLicenseBuildConfig = {
  serverUrl: "https://shuncode-bridge-license.2357872806.workers.dev",
  issuer: "https://shuncode-bridge-license.2357872806.workers.dev",
  audience: "shuncode-desktop",
  publicKeyPem: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA/qdDfaXj+J29Lv+3rlUFD5DeZXJDGVm2ERuK6V1zLSU=\n-----END PUBLIC KEY-----\n",
  // Gitee application client id (https://gitee.com/oauth/applications).
  giteeClientId: "7bfd24d05dd2b09c00f152d614fea2e0ed8befc1e3b1dfea9c48fadf50b61c4f",
};
